### ISSUE TITLE
SubNav-导航支持图片预览

### ISSUE THREAD

**Issue by yszhblog** [JoeyBling/hexo-theme-yilia-plus#1]
如图：![images](https://user-images.githubusercontent.com/49360964/62337732-73e0f800-b508-11e9-9b04-a469a2d5e93a.png)我想把这个微信,鼠标经过是二维码图片预览

**Comment by JoeyBling** [comment]
最新版本已添加支持，请拉取最新代码！谢谢支持
> 请配置 `hover_effect`
