### ISSUE TITLE
添加标签页面无效

### ISSUE THREAD

**Issue by yansheng836** [JoeyBling/hexo-theme-yilia-plus#11]
## ❓问题
添加标签页面`hexo new page tags`无效，网上很多都说这样就可以直接生成有标签的页面，而我的却不行；我不知道是不是我在配置的时候删除了什么文件造成的？想问下有没有人遇到过同样的问题？

### 结果
在执行`hexo g`后生成的`\public\tags\index.html`文件中却没有标签的相关内容（注：已有文章中存在有tag属性），所以显示的压根就只是一个空白页（如下图）：
![image](https://user-images.githubusercontent.com/45334066/63222504-84b58d00-c1db-11e9-8e83-8a88249a0d88.png)

和tags页面一样，categories页面也显示不出来。

---
而对于`归档: /archives`页面好像只需要在配置文件中开启设置就可以了（这个功能好像内置了），查看了下source目录是没有/archives目录，而`public\archives\index.html`里面却是有归档内容，所以归档页面可以显示归档信息。

### 预期
标签页面能够正常显示，就和归档页面一样。
![image](https://user-images.githubusercontent.com/45334066/63222773-9cdadb80-c1de-11e9-95fc-72a55deb20dc.png)
Please describe what you expected to see.(请描述一下你希望看到什么)

## 🐥环境 & 设置

**Node.js & npm version**

```bash
$ node -v
v10.16.0

$ npm -v
6.9.0
```

**Your theme `_config.yml`** (Optional)

添加标签页面`hexo new page tags`，会在生成`\source\tags\index.md`文件，编辑的内容为：
```
---
title: tags
date: 2019-07-30 10:11:45
type: tags
comments: false
---
```
同时在配置文件`\themes\yilia\_config.yml`中设置：
```yml
menu:
  主页: /
  #随笔: /tags/随笔/
  分类: /categories
  归档: /archives
  相册: /photos
  标签: /tags
```

**Comment by yansheng836** [comment]
问题已解决，可参考：<https://github.com/litten/hexo-theme-yilia/issues/835#issuecomment-522636671>

**Comment by JoeyBling** [comment]
这个本身yilia主题是没有添加支持的，暂时不打算集成到主题来，后续看情况再定
