### ISSUE TITLE
音乐建议添加多种平台

### ISSUE THREAD

**Issue by yszhblog** [JoeyBling/hexo-theme-yilia-plus#12]
比如”网易、腾讯、酷狗、虾米、百度“

**Comment by JoeyBling** [comment]
需求太特殊了，暂时不打算支持，如果需自定义模板，建议 fork，参考[wiki](https://github.com/JoeyBling/hexo-theme-yilia-plus/wiki/yilia-plus%E6%BA%90%E7%A0%81%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84%E5%8F%8A%E6%9E%84%E5%BB%BA%E9%A1%BB%E7%9F%A5)自行修改

> 后面看情况也有可能会加入此功能
