### ISSUE TITLE
有序列表和无序列表嵌套使用的问题

### ISSUE THREAD

**Issue by littlesulley** [JoeyBling/hexo-theme-yilia-plus#13]
如图
![](https://github.com/littlesulley/pics-for-articles/blob/master/1.png?raw=true)

**Comment by JoeyBling** [comment]
@littlesulley 你把源码贴出来我看看，这个应该是本身MarkDown语法不支持的问题

**Comment by littlesulley** [comment]
![image](https://user-images.githubusercontent.com/35071593/63407003-101e6080-c41e-11e9-8107-40f5a97c2fe7.png)
这是我本地VSCODE上编辑的~

**Comment by JoeyBling** [comment]
@littlesulley 我刚刚更新了代码，你拉取下仓库最新代码，看看能不能解决你的问题！

**Comment by littlesulley** [comment]
嗯... 好像还是不行惹😂

**Comment by JoeyBling** [comment]
@littlesulley 你把你的Markdown代码发我，我在我这里试试

**Comment by littlesulley** [comment]
发个简单的吧~
==========
1. 这是有序列表1
   - 这是无序列表1.1
   - 这是无序列表1.2
     - 这是无序列表 1.2.1
     - 这是无序列表 1.2.2
2. 这是有序列表2
   - 这是无序列表2.1
   - 这是无序列表2.2
3. 这是有序列表3
4. 这是有序列表4 
==========
多谢 😂

**Comment by littlesulley** [comment]
```python
1. 这是有序列表1
   - 这是无序列表1.1
   - 这是无序列表1.2
     - 这是无序列表 1.2.1
     - 这是无序列表 1.2.2
2. 这是有序列表2
   - 这是无序列表2.1
   - 这是无序列表2.2
3. 这是有序列表3
4. 这是有序列表4 
```
😂忘了用引用了

**Comment by JoeyBling** [comment]
我测试了没有问题啊

**Comment by littlesulley** [comment]
好的，多谢~ 应该是有地方我没改好，我把这个issue关了~🥰

**Comment by JoeyBling** [comment]
嗯，你检查一下，看看是不是哪里配错了，如果没有问题的话麻烦和我说一样

**Comment by littlesulley** [comment]
没问题了，感谢~！

**Comment by JoeyBling** [comment]
@littlesulley 没事，谢谢你的反馈
