### ISSUE TITLE
文章的分类和标签创建后不会归类

### ISSUE THREAD

**Issue by xiuxiumomo** [JoeyBling/hexo-theme-yilia-plus#16]
## ❓问题
创建了categories 和tags然后其下面的index.md也做了相应设置，发表的文章添加了不同的标签和分类，点击分类或标签页面是空的

## 🤔结果 & 预期

分类下应该会统计有几个分类，标签下应该会显示几个标签

## 🙋Others

~~~
categories/index.md
---
title: 分类
date: 2019-08-22 21:24:05
type: "categories"
layout: "categories"
---

post文章
---
title: reat入门
tags: 
- react 
categories: 
- react
---
react文章
~~~

**Comment by xiuxiumomo** [comment]
eeee,上传到git上又可以打开了，刚刚是本地调试不显示~~~尴尬，尴尬

**Comment by JoeyBling** [comment]
这个肯定不会出现git仓库和本地不同步的问题，应该是你浏览器缓存的原因或者hexo的问题，你试试清除下浏览器缓存，然后使用```hexo clean```再执行```hexo s -g```预览下，看看问题是否还存在

> **参考`Front-matter`**

```json
---
categories:
  - 分类
tags:
  - 标签1
---
```

**Comment by JoeyBling** [comment]
关于标签页面无效请参考 > https://github.com/JoeyBling/hexo-theme-yilia-plus/issues/11

**Comment by xiuxiumomo** [comment]
问题解决了。就是首页文章在哪设置只预览文章的前面几段，现在首页会显示全文。

**Comment by JoeyBling** [comment]
关于文章进行裁剪请参考 > https://github.com/JoeyBling/hexo-theme-yilia-plus/issues/7

**Comment by xiuxiumomo** [comment]
> 关于文章进行裁剪请参考 > #7

我已经找到了，谢谢哈。
