### ISSUE TITLE
BLOG背景图片

### ISSUE THREAD

**Issue by littlesulley** [JoeyBling/hexo-theme-yilia-plus#18]
请问怎么修改blog背景呢？（现在是纯白的）

**Comment by JoeyBling** [comment]
@littlesulley 暂时不支持修改

**Comment by yansheng836** [comment]
如果有需要，可参考这位兄弟的博客进行修改 ：<https://cqh-i.github.io/>

![image](https://user-images.githubusercontent.com/45334066/64226253-3c9fa580-cf11-11e9-8626-fd90f1314250.png)

**Comment by littlesulley** [comment]
@yansheng836 好的，多谢！
