### ISSUE TITLE
文章内分页

### ISSUE THREAD

**Issue by littlesulley** [JoeyBling/hexo-theme-yilia-plus#19]
是否可以考虑加一个文章内分页的功能呢？
当文章很长的时候，页面加载会变慢（尤其是公式很多的时候），而且也不方便其他人保存阅读进度。
比如文章有十章，可以每一章分一个页面（在文章底部有页面选项），比如可以以`<!-- page -->`作为页面分隔。（不知道能不能实现，我猜想的。）

**Comment by JoeyBling** [comment]
> 是否可以考虑加一个文章内分页的功能呢？
> 当文章很长的时候，页面加载会变慢（尤其是公式很多的时候），而且也不方便其他人保存阅读进度。
> 比如文章有十章，可以每一章分一个页面（在文章底部有页面选项），比如可以以`<!-- page -->`作为页面分隔。（不知道能不能实现，我猜想的。）

这个应该不太好实现吧，我暂时没有看过那个静态网站生成器有这个功能，没啥思路，后面我留意下吧，看看能不能找到方法解决

**Comment by littlesulley** [comment]
好~感谢作者~！
