### ISSUE TITLE
网易云音乐没有头像，还建议下部添加一些文字

### ISSUE THREAD

**Issue by yszhblog** [JoeyBling/hexo-theme-yilia-plus#2]
是否可以考虑支持配置开启头像和下部添加一些文字 例如：
![466@C_Y(Q@H 5H9Z{ G4$3G](https://user-images.githubusercontent.com/49360964/62338619-b8ba5e00-b50b-11e9-8404-6378de58a6be.png)

**Comment by JoeyBling** [comment]
最新版本已添加支持，请拉取最新代码！谢谢支持
