### ISSUE TITLE
文章如何显示部分内容

### ISSUE THREAD

**Issue by warmfrog** [JoeyBling/hexo-theme-yilia-plus#24]
## ❓问题
我在 Hexo 博客中应用该主题后，文章列表中，文章过长，没有收缩。地址：h ttps://warmfrog.github.io. 主题配置中的 excerpt_link: more 好像没起作用

## 🤔结果 & 预期

Please describe what you expected to see.(请描述一下你希望看到什么)

## 🐥环境 & 设置

**Node.js & npm version**

```bash
```

**Your site `_config.yml`** (Optional)

```yml
```

**Your theme `_config.yml`** (Optional)

```yml
```

**Your browsers** (Optional)

> The browser you use

**Your OSes** (Optional)

> what platforms (operating systems and devices) are affected?

**Comment by JoeyBling** [comment]
@warmfrog `excerpt_link`配置用来做截断标识，在你`markdown`文件需要截断的行增加此标记：`<!--more-->`

**Comment by warmfrog** [comment]
原来是这个意思。果然可以了！谢谢。
