### ISSUE TITLE
iPad 左侧排版问题

### ISSUE THREAD

**Issue by yszhblog** [JoeyBling/hexo-theme-yilia-plus#3]
使用iPad打开时，看不到下面的导航栏，是否可以优化下支持滚动条或者其他方式
![~ 5OXXS7Q$4%UEMUF1X3$WU](https://user-images.githubusercontent.com/49360964/62338677-f0c1a100-b50b-11e9-8fc5-8163d7ea5ead.png)

**Comment by JoeyBling** [comment]
最新版本已添加支持，请拉取最新代码！谢谢支持
