### ISSUE TITLE
我看了下你的博客, 我发现文章都是外链的形式, 是设计如此吗？

### ISSUE THREAD

**Issue by wangdabaoqq** [JoeyBling/hexo-theme-yilia-plus#30]

**Comment by wangdabaoqq** [comment]
抱歉。
我看到了配置项, 可以关闭了这个。

**Comment by JoeyBling** [comment]
你意思是说文章会在新窗口打开吗？还是说文章里的内容链接都是外链？
- 如果是在新窗口打开的话可以通过配置开启：`open_in_new`
- 如果是文章里的内容链接是根据你`Markdown`内容来生成的

**Comment by JoeyBling** [comment]
嗯，好，谢谢支持！
