### ISSUE TITLE
所有文章、关于我 这些按钮 点击会出现弹出新标签页 

### ISSUE THREAD

**Issue by subaobaos** [JoeyBling/hexo-theme-yilia-plus#34]
之前降低版本的回答 经过测试依旧存在

**Comment by JoeyBling** [comment]
@subaobaos 请贴下你的站点地址，以及根目录`package.json`文件的内容.

**Comment by hello886** [comment]
我的也是

**Comment by JoeyBling** [comment]
@hello886 请参考[https://github.com/JoeyBling/hexo-theme-yilia-plus/issues/33](https://github.com/JoeyBling/hexo-theme-yilia-plus/issues/33)

**Comment by hello886** [comment]
@JoeyBling  变成白页了

**Comment by JoeyBling** [comment]
@hello886 贴下你根目录`_config.yml`的配置，以及`package.json`文件的内容，还有网址也发我看下

**Comment by hello886** [comment]
_config.yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Hexo
subtitle: ''
description: ''
keywords:
author: John Doe
language: en
timezone: ''

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing index.html from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
#include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: yilia-plus

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
    type: git
    repo: git@github.com:hello886/hello886.github.io.git
    branch: master

jsonContent:
    meta: false
    pages: false
    posts:
      title: true
      date: true
      path: true
      text: false
      raw: false
      content: false
      slug: false
      updated: false
      comments: false
      link: false
      permalink: false
      excerpt: false
      categories: false
      tags: true

package.json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "3.9.0"
  },
  "dependencies": {
    "hexo": "^3.9.0",
    "hexo-deployer-git": "^2.1.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-json-content": "^4.1.6",
    "hexo-generator-tag": "^1.0.0",
    "hexo-migrator-wordpress": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^2.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0"
  }
}

网址：
github：https://github.com/hello886/hello886.github.io
网页：hello886.github.io

**Comment by hello886** [comment]
@JoeyBling

**Comment by JoeyBling** [comment]
还有`package.json`文件

**Comment by JoeyBling** [comment]
@hello886 你本地预览的时候会有问题吗?

**Comment by hello886** [comment]
@JoeyBling  我没预览，直接跑的，我预览试试

**Comment by hello886** [comment]
@JoeyBling  也是空的，预览页不行

**Comment by JoeyBling** [comment]
> @JoeyBling 也是空的，预览页不行

好的，我看看问题

**Comment by hello886** [comment]
解决了，这个时yilia的问题，你基于他做的修改，自然也有同样问题。
```
在..\themes\yilia\layout_partial\left-col.ejs中

<nav class="header-smart-menu">
    		<% for (var i in theme.smart_menu){ %>
    			<% if(theme.smart_menu[i]){ %>
    			<a q-on="click: openSlider(e, '<%-i%>')" target="_self" href="javascript:void(0)"><%= theme.smart_menu[i] %></a>
    			<% } %>
            <%}%>
		</nav>
```

参考了：https://github.com/litten/hexo-theme-yilia/issues/852

**Comment by JoeyBling** [comment]
@hello886 需要注释掉根目录`_config.yml`文件的`include`、`exclude`、`ignore`配置

**Comment by JoeyBling** [comment]
@subaobaos 我更新了使用操作，参考 https://github.com/JoeyBling/hexo-theme-yilia-plus/issues/33

**Comment by imdreamer2018** [comment]
![image](https://user-images.githubusercontent.com/35443799/75625817-951fd900-5bfc-11ea-99d1-86c17e70b755.png)
为什么我这里所有文章，点的是空白，也不能搜索，然后点击旁边的空白关闭不了这个所有文章菜单。

**Comment by JoeyBling** [comment]
@imdreamer2018 `mathjax`配置项错误，是`true`不是`ture`

**Comment by imdreamer2018** [comment]
> @imdreamer2018 `mathjax`配置项错误，是`true`不是`ture`

emmmm，犯这种低级错误。谢谢你。。。

**Comment by JoeyBling** [comment]
没事，正常的。我也会犯，重要的是要debug发现错误
