### ISSUE TITLE
上一页和下一页的问题

### ISSUE THREAD

**Issue by wang-jie-feng** [JoeyBling/hexo-theme-yilia-plus#35]
## ❓问题
分页的按钮，总是渲染不出来大概是这样子
![image](https://user-images.githubusercontent.com/51876176/69519023-f7c95f00-0f93-11ea-82b9-f5877473624f.png)

## 🤔结果 & 预期

Please describe what you expected to see.(请描述一下你希望看到什么)

## 🐥环境 & 设置

**Node.js & npm version**

```bash
npm -v 6.11.3
Node.js -v v12.12.0.
```

**Your site `_config.yml`** (Optional)

```yml
```

**Your theme `_config.yml`** (Optional)

```yml
```

**Your browsers** (Optional)

> The browser you use

**Your OSes** (Optional)

> what platforms (operating systems and devices) are affected?

**Comment by JoeyBling** [comment]
@wang-jie-feng 贴一下地址

**Comment by wang-jie-feng** [comment]
博客地址
www.wangjiefeng.cn



jiefengfire@163.com
 
发件人： 思伟
发送时间： 2019-11-25 15:10
收件人： JoeyBling/hexo-theme-yilia-plus
抄送： wang-jie-feng; Author
主题： Re: [JoeyBling/hexo-theme-yilia-plus] 上一页和下一页的问题 (#35)
@wang-jie-feng 贴一下地址

**Comment by JoeyBling** [comment]
有改过源码吗?

**Comment by JoeyBling** [comment]
根目录下`package.json`内容发一下

**Comment by wang-jie-feng** [comment]
好像改过一点，只是将github那个小图标去掉了，但是之前并没有问题，而且我看的控制台好像html代码是没有问题的，可是浏览器代码并没有渲染出来



jiefengfire@163.com
 
发件人： 思伟
发送时间： 2019-11-25 15:41
收件人： JoeyBling/hexo-theme-yilia-plus
抄送： wang-jie-feng; Mention
主题： Re: [JoeyBling/hexo-theme-yilia-plus] 上一页和下一页的问题 (#35)
根目录下package.json内容发一下

**Comment by JoeyBling** [comment]
根目录下`package.json`内容发一下，有可能是新版API改动了的原因

**Comment by wang-jie-feng** [comment]
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "4.0.0"
  },
  "dependencies": {
    "hexo": "^4.0.0",
    "hexo-deployer-git": "^2.0.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-feed": "^2.0.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-json-content": "^4.1.6",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-jade": "^0.5.0",
    "hexo-renderer-marked": "^2.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0"
  }
}

刚才那个回复的邮件是有附件的
这是里边的内容


jiefengfire@163.com
 
发件人： 思伟
发送时间： 2019-11-25 15:48
收件人： JoeyBling/hexo-theme-yilia-plus
抄送： wang-jie-feng; Mention
主题： Re: [JoeyBling/hexo-theme-yilia-plus] 上一页和下一页的问题 (#35)
根目录下package.json内容发一下，有可能是新版API改动了的原因

**Comment by JoeyBling** [comment]
@wang-jie-feng 经测试，版本太高，建议使用`3.9.0`版本，请参考 #33

**Comment by wang-jie-feng** [comment]
已解决，万分感谢
