### ISSUE TITLE
你好，请问为什么邮箱不能打开呢

### ISSUE THREAD

**Issue by whiteS18** [JoeyBling/hexo-theme-yilia-plus#36]
## ❓问题

你好，我在使用这个主题的时候，在subNav中去掉了email的#，其他什么也没有动。然后我hexo clean,hexo g,hexo s
本地访问4000端口，点击了邮箱的图标，
结果却提示Cannot GET /mailto:zhousiwei0911@qq.com
## 🤔结果 & 预期

Please describe what you expected to see.(请描述一下你希望看到什么)
我希望能正常的打开邮箱的软件

## 🐥环境 & 设置

**Node.js & npm version**
$ node -v
v10.16.0

```bash
```$ bash --version
bash --version
GNU bash, version 4.4.19(2)-release (x86_64-pc-msys)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>


**Your browsers** (Optional)

> The browser you use
ie edge
chrome

**Comment by yansheng836** [comment]
你看下是不是系统问题，我（Windows系统）点击上面的这个超链接，直接跳出一个发邮箱的界面，如下：
![image](https://user-images.githubusercontent.com/45334066/69913050-f0132a00-146d-11ea-8dd4-7b408eaa6bb4.png)

**Comment by whiteS18** [comment]
> 你看下是不是系统问题，我（Windows系统）点击上面的这个超链接，直接跳出一个发邮箱的界面，如下：
> ![image](https://user-images.githubusercontent.com/45334066/69913050-f0132a00-146d-11ea-8dd4-7b408eaa6bb4.png)

我也是windows系统，点击超链接本地他弹出的就是Cannot GET /mailto:zhousiwei0911@qq.com，githubpage上就是404，浏览器的显示网址是https://cwsong.top/mailto:litten225@qq.com，我将mailto前面的都去掉他就能正常跳出邮箱发送界面了，感觉是配置文件的原因，但一直找不出来是哪儿，有的用了该主题的博客我点击过，有的是好的，可以正常弹出，您具体可以访问cwsong.top上点击邮箱超链接试试，不知道您电脑上是否能正常弹出邮件发送界面

**Comment by yansheng836** [comment]
不用加`/`，直接`mailto:litten225@qq.com`

**Comment by yansheng836** [comment]
还有超链接最好加尖括号，如：`<url>`，不然可能会出现错误，比如你上面的评论

**Comment by whiteS18** [comment]
> 你看下是不是系统问题，我（Windows系统）点击上面的这个超链接，直接跳出一个发邮箱的界面，如下：
> ![image](https://user-images.githubusercontent.com/45334066/69913050-f0132a00-146d-11ea-8dd4-7b408eaa6bb4.png)

刚刚对比看了下我们俩的超链接，发现我的前面多了一个/，

> 还有超链接最好加尖括号，如：`<url>`，不然可能会出现错误，比如你上面的评论

好的...但是我的mailto在`_config.yml`中没有加上`/`，但是他在生成网页后自己带上了，请问这个该去哪里设置呢
![捕获](https://user-images.githubusercontent.com/31566522/69914592-fa8aef00-1480-11ea-9a90-33ba93f8cffe.PNG)
![捕获1](https://user-images.githubusercontent.com/31566522/69914593-fb238580-1480-11ea-9af0-d21b291d0f04.PNG)

**Comment by yansheng836** [comment]
额，这个可能是版本更新造成的问题。

源码：`themes\yilia\layout\_partial\left-col.ejs`,（我的）相关代码
```html
<nav class="header-nav">
	<div class="social">
	     <% for (var i in theme.subnav){ %>
		<a class="<%= i %>" target="_blank" href="<%- url_for(theme.subnav[i]) %>" title="<%= i %>"><i class="icon-<%= i %>"></i></a>
		<%}%>
	</div>
```

具体怎么改，我也不太清楚啊……

**Comment by whiteS18** [comment]
我的源码好像不一样....
```
		<nav class="header-nav">
			  <div class="social">
				  <% for (var i in theme.subNav){ %>
					  <a class="<%= i %>" href="<%- url_for(theme.subNav[i]) %>" title="<% if (__('subNav.title.'+ i)){ %><%= __('subNav.title.'+ i) %><% } else { %><%= i %><% } %>" <% if (theme.open_in_new.subNav){ %>target="_blank"<% } %>><i class="icon-<%= i %>"></i></a>
			  	<%}%>
			  </div>
```

**Comment by yansheng836** [comment]
我用的是`yilia`，你试下其他会不会有问题，比如填下github地址。

**Comment by whiteS18** [comment]
> 我用的是`yilia`，你试下其他会不会有问题，比如填下github地址。
我把我的那一部分代码换成了你的，然后重新试了下，依旧是无法正确打开应用，然后吧链接改成知乎主页，一个Http的网址，是正常的

**Comment by yansheng836** [comment]
猜测应该是另一个可能原因：subNav里面，先检测值是否是一个网址（可能是检测协议、`:`、`//`），如果是，就原样输出；如果不是，自动添加`/`，把它当做一个相对于网站目录的文件，比如RSS订阅的文件：`rss: "atom.xml"`-->"https://you.com/atom.xml"。

而这个`mailto:111111111@qq.com`应该是被当做后者了。

**Comment by whiteS18** [comment]
比较奇怪的是其他人的为什么就可以正常访问呢...比如你的。。。

**Comment by yansheng836** [comment]
额，上面我也提到了，这个可能是版本更新造成的问题，比如hexo版本、相关插件的版本等。

**Comment by whiteS18** [comment]
额。。。能发下你的版本吗我对比下

**Comment by whiteS18** [comment]
我的是
```
$ hexo  -v
hexo: 4.0.0
hexo-cli: 3.1.0
os: Windows_NT 10.0.18362 win32 x64
http_parser: 2.8.0
node: 10.16.0
v8: 6.8.275.32-node.52
uv: 1.28.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 64
nghttp2: 1.34.0
napi: 4
openssl: 1.1.1b
icu: 64.2
unicode: 12.1
cldr: 35.1
tz: 2019a

```

**Comment by whiteS18** [comment]
我的站点package-json是
```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server",
    "publish": "hexo cl && hexo g &&  hexo d",
    "view": "hexo cl && hexo g && hexo s"
  },
  "hexo": {
    "version": "4.0.0"
  },
  "dependencies": {
    "hexo": "^4.0.0",
    "hexo-deployer-git": "^2.1.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-baidu-sitemap": "^0.1.6",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-json-content": "^4.1.6",
    "hexo-generator-sitemap": "^1.2.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^2.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0"
  }
}

```

**Comment by yansheng836** [comment]
hexo
```shell
$ hexo -v
(node:145956) [DEP0061] DeprecationWarning: fs.SyncWriteStream is deprecated.
hexo: 3.9.0
hexo-cli: 2.0.0
os: Windows_NT 10.0.17763 win32 x64
http_parser: 2.8.0
node: 10.16.0
v8: 6.8.275.32-node.52
uv: 1.28.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 64
nghttp2: 1.34.0
napi: 4
openssl: 1.1.1b
icu: 64.2
unicode: 12.1
cldr: 35.1
tz: 2019a
```
package.json
```json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.9.0"
  },
  "dependencies": {
    "hexo": "^3.9.0",
    "hexo-abbrlink": "^2.0.5",
    "hexo-admin": "^2.3.0",
    "hexo-baidu-url-submit": "0.0.6",
    "hexo-deployer-git": "^2.0.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-baidu-sitemap": "^0.1.6",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^2.0.0",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-json-content": "^4.1.6",
    "hexo-generator-sitemap": "^1.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-helper-live2d": "^3.1.1",
    "hexo-neat": "^1.0.4",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-markdown-it": "^3.4.1",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.3",
    "hexo-wordcount": "^6.0.1",
    "live2d-widget-model-hijiki": "^1.0.5",
    "markdown-it-emoji": "^1.4.0"
  }
}

```

**Comment by JoeyBling** [comment]
@whiteS18 经测试，最近`hexo`版本更新了，但是存在一点问题，请统一参考[https://github.com/JoeyBling/hexo-theme-yilia-plus/issues/33](https://github.com/JoeyBling/hexo-theme-yilia-plus/issues/33)进行降低版本

**Comment by whiteS18** [comment]
已解决，我就先关闭了 @JoeyBling
