### ISSUE TITLE
上传博客备份到另一个分支后，github检测出漏洞，请问如何处理呢？

### ISSUE THREAD

**Issue by GeorgeJu95** [JoeyBling/hexo-theme-yilia-plus#37]
![微信截图_20191206101226](https://user-images.githubusercontent.com/49896926/70289964-68347380-1811-11ea-8136-7ab1500cddb7.png)

**Comment by JoeyBling** [comment]
这是`Npm`有些依赖的版本好像有些安全警告，你可以点击忽略，也可以修复。影响不大
> 忽略点击`Dismiss all`
