### ISSUE TITLE
webpack打包提示 options has an unknown property 'autoprefixer'.

### ISSUE THREAD

**Issue by timesina** [JoeyBling/hexo-theme-yilia-plus#39]
![20191219172627](https://user-images.githubusercontent.com/20322044/71161892-2aa9fe80-2285-11ea-912a-ce1d1d937ec9.png)
![20191219172732](https://user-images.githubusercontent.com/20322044/71161893-2aa9fe80-2285-11ea-90c7-0fec20ed7b4e.png)

不太会webpack 调整样式后如何使用

**Comment by JoeyBling** [comment]
@timesina 参考[yilia-plus源码目录结构及构建须知](https://github.com/JoeyBling/hexo-theme-yilia-plus/wiki/yilia-plus%E6%BA%90%E7%A0%81%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84%E5%8F%8A%E6%9E%84%E5%BB%BA%E9%A1%BB%E7%9F%A5)

**发布命令**``npm run dist``

**Comment by timesina** [comment]
可以了，之前把包更新了导致打包失败

**Comment by JoeyBling** [comment]
> 可以了，之前把包更新了导致打包失败

应该是更新了npm的依赖了吧
