### ISSUE TITLE
返回顶部的图标不显示

### ISSUE THREAD

**Issue by jackandsnow** [JoeyBling/hexo-theme-yilia-plus#41]
## ❓问题
返回顶部的图标不显示

你好，今天使用了这个theme，但是发现返回顶部的图标无法显示，请问这个什么原因呢？

## 🤔结果 & 预期
还望楼主能够看看，帮助我解决下

Please describe what you expected to see.(请描述一下你希望看到什么)

## 🐥环境 & 设置

**Node.js & npm version**

```bash
```

**Your site `_config.yml`** (Optional)

```yml
```

**Your theme `_config.yml`** (Optional)

```yml
```

**Your browsers** (Optional)

> The browser you use

**Your OSes** (Optional)

> what platforms (operating systems and devices) are affected?

**Comment by JoeyBling** [comment]
@jackandsnow 是最新拉取的代码吗？如果不是更新下，还不行请贴下你博客地址

**Comment by jackandsnow** [comment]
是最新的代码，博客地址 https://jackandsnow.github.io/

**Comment by jackandsnow** [comment]
@JoeyBling 是最新的代码，博客地址 https://jackandsnow.github.io/

**Comment by jackandsnow** [comment]
@JoeyBling 另外还有个问题问下，文章目录的自动编号怎么去掉啊？toc_hide_index已经是 true了

**Comment by JoeyBling** [comment]
@jackandsnow 配置文件少了`open_in_new`项，是不是被你删掉了

**Comment by jackandsnow** [comment]
@JoeyBling 我置为false了，以为这个只是新标签打开，这个对其他有影响吗

**Comment by JoeyBling** [comment]
@jackandsnow 我看看你的配置，截图

**Comment by JoeyBling** [comment]
@jackandsnow 错了，新版本改了一点变化，
![](https://user-images.githubusercontent.com/25240064/72406071-f814f800-3795-11ea-99de-f5d09e9d44ec.png)，请比对下文件

**Comment by JoeyBling** [comment]
```yaml
# Open link in a new tab | 是否在新窗口打开链接
open_in_new:
  article: true  # 文章链接
  menu: true   # 导航菜单
  subNav: true  # 子菜单
```

**Comment by jackandsnow** [comment]
对的，这个我改回去正常了，我之前是直接 
open_in_new: false

**Comment by JoeyBling** [comment]
@jackandsnow 是的，我后面升级版本的时候做了配置文件的更新，但是没仔细标明，我后面看看有没有什么方法优化的

**Comment by jackandsnow** [comment]
好的，感谢楼主信息解答，等待楼主新的优化

**Comment by jackandsnow** [comment]
好的，感谢楼主细心解答，等待楼主新的优化~
