### ISSUE TITLE
hexo g打印太多yilia-plus的插件，原yilia没有，可以去掉吗？太刺眼

### ISSUE THREAD

**Issue by wkzqn** [JoeyBling/hexo-theme-yilia-plus#44]
## 🤔结果 & 预期

Please describe what you expected to see.(请描述一下你希望看到什么)

## 🐥环境 & 设置

**Node.js & npm version**

```bash
```

**Your site `_config.yml`** (Optional)

```yml
```

**Your theme `_config.yml`** (Optional)

```yml
```

**Your browsers** (Optional)

> The browser you use

**Your OSes** (Optional)

> what platforms (operating systems and devices) are affected?

**Comment by JoeyBling** [comment]
截图提供以下

**Comment by wkzqn** [comment]
说错了，是打印太多hexo-plus的日志

**Comment by wkzqn** [comment]
![image](https://user-images.githubusercontent.com/44158381/75135034-2c77be80-571b-11ea-9670-dd9dceaa741b.png)
类似于zhe这种

**Comment by JoeyBling** [comment]
在`default_config.js`文件中，把`log.enable`属性关掉

**Comment by wkzqn** [comment]
好勒，谢谢你哈，我的问题解决了。
