### ISSUE TITLE
有序列表嵌套问题

### ISSUE THREAD

**Issue by wkzqn** [JoeyBling/hexo-theme-yilia-plus#45]
1. 下面这张图是我在typora上编辑的样式
![image](https://user-images.githubusercontent.com/44158381/75609584-e40a3780-5b44-11ea-99f1-b67ad582c276.png)
2. 但是在yilia-plus上显示是这样子的
![image](https://user-images.githubusercontent.com/44158381/75609601-11ef7c00-5b45-11ea-8415-8009d58f7780.png)
3.下面这个是我的case
https://wkzqn.club/2020/02/16/%E6%B5%8B%E8%AF%95/

**Comment by wkzqn** [comment]
无序列表嵌套同样存在问题
![image](https://user-images.githubusercontent.com/44158381/75609802-72cb8400-5b46-11ea-92d8-17fcbf43deb9.png)
![image](https://user-images.githubusercontent.com/44158381/75609808-837bfa00-5b46-11ea-99e6-4fbaebce4c51.png)

**Comment by wkzqn** [comment]
![image](https://user-images.githubusercontent.com/44158381/75628124-f81b6b00-5c10-11ea-8614-1ffde5062be4.png)
经检查是b8fa34.css文件中的list-style属性导致。

**Comment by JoeyBling** [comment]
列表嵌套问题确实存在Bug，这块要花点时间调下

**Comment by JoeyBling** [comment]
感谢反馈

**Comment by wkzqn** [comment]
把list-style删掉就好了。
