### ISSUE TITLE
请问下网易云音乐可以添加多首音乐吗？

### ISSUE THREAD

**Issue by wkzqn** [JoeyBling/hexo-theme-yilia-plus#46]

**Comment by wkzqn** [comment]
![image](https://user-images.githubusercontent.com/44158381/75676564-6ec57080-5cc4-11ea-8ccd-0c184bfdd15f.png)

**Comment by JoeyBling** [comment]
不能，且版权是未受保护的

**Comment by wkzqn** [comment]
好吧


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: 思伟 <notifications@github.com&gt;
发送时间: 2020年3月3日 09:09
收件人: JoeyBling/hexo-theme-yilia-plus <hexo-theme-yilia-plus@noreply.github.com&gt;
抄送: wkzqn <206878258@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[JoeyBling/hexo-theme-yilia-plus] 请问下网易云音乐可以添加多首音乐吗？ (#46)
