### ISSUE TITLE
yilia_plus_full_url 对 https未处理

### ISSUE THREAD

**Issue by csliubo** [JoeyBling/hexo-theme-yilia-plus#47]
## ❓问题

.config.yml 里 url 的schema如果是https，yilia_plus_full_url 生成的结果是错的。
假如url里配置的是： https://aaa.github.io
最后生成的是： https:/aaa.github.io/ 

具体原因是 scripts/helpers/yilia-plus-vendors.js 里的这段代码，在最后替换的时候并未将https考虑进去
```
  let fullUrl = (blogUrl + url).replace(/(\\|\/){2,}/g, '/')
    .replace(/((ht|f)tp\:(\\|\/)+)/ig, 'http://');
```

## 🤔结果 & 预期
预期生成结果是: https://aaa.github.io/

**Comment by JoeyBling** [comment]
感谢反馈，新版本已解决！
