### ISSUE TITLE
文章在首页无法折叠

### ISSUE THREAD

**Issue by SuyueLiu** [JoeyBling/hexo-theme-yilia-plus#48]
## ❓问题

你好，想请教一下怎么样让文章在首页只显示一部分？我已经在_config里面开启了相应的功能，但是还是不行。

## 🐥环境 & 设置

node.js v12.16.1
Npm 6.13.4

<img width="466" alt="截屏2020-04-08 上午1 07 23" src="https://user-images.githubusercontent.com/49122192/78730755-ae235480-7935-11ea-9261-abb2850ade05.png">

**Comment by JoeyBling** [comment]
在要截断的文章代码中，增加标记代码即可
> `<!--more-->`

**Comment by SuyueLiu** [comment]
我明白了，谢谢！
