### ISSUE TITLE
添加了内容如何重新编译项目

### ISSUE THREAD

**Issue by huaxiaoer** [JoeyBling/hexo-theme-yilia-plus#51]
## ❓问题
首先很抱歉， 因为我希望按自己的想法定制一下主题， 所以被迫需要修改大佬的代码里的`source-src/js/main.js`文件， 请问题修改了文件后怎么才能生效？

因为我想在blog中添加 有**分类层次结构**， 所以引入了`hexo-plugin-hierarchy-category` 插件。  
因此需要在项目中的`source-src/js/main.js` 文件添加如下代码：
```
import getHCateHelpers from "hexo-plugin-hierarchy-category";
const util = getHCateHelpers(hexo);
``` 

## 🤔结果 & 预期

希望分类页能展示分类层次结构

## 🐥环境 & 设置

**Node.js & npm version**

```bash
$ npm -v
6.14.4
$ node -v
v13.14.0
```

**Your OSes** (Optional)
> macos 15

**Comment by JoeyBling** [comment]
参考[WIFI](https://github.com/JoeyBling/hexo-theme-yilia-plus/wiki)
> [源码目录结构及构建须知](https://github.com/JoeyBling/hexo-theme-yilia-plus/wiki/yilia-plus%E6%BA%90%E7%A0%81%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84%E5%8F%8A%E6%9E%84%E5%BB%BA%E9%A1%BB%E7%9F%A5#%E5%9B%9B%E5%BC%80%E5%8F%91%E6%AD%A5%E9%AA%A4)

**Comment by huaxiaoer** [comment]
之前没注意有wiki， 我先看看，谢谢
