### ISSUE TITLE
用git管理博客的本地文件自后仓库出现dependence alerts

### ISSUE THREAD

**Issue by SuyueLiu** [JoeyBling/hexo-theme-yilia-plus#52]
## ❓问题

你好，我在用git管理博客的本地文件之后，github的仓库出现alerts。我的具体做法是：
1. 在repository里面创建一个新的branch并设置为default，然后clone到本地；
2. 删除除 **.git** 文件以外的所有文件，并把原来博客本地文件夹里面的东西全部复制过来，提交commit之后出现alters，theme文件里面的.git文件在合并之前已删除。
3. alerts指向 `.../yilia-plus/package-lock.json`

<img width="834" alt="截屏2020-06-07 上午11 01 41" src="https://user-images.githubusercontent.com/49122192/83965820-485c3600-a8ae-11ea-9318-3c161739f941.png">

## 🐥环境 & 设置

**Node.js & npm version**

node: v12.16.1
npm 6.13.4

## 🙋Others

我用 `npm ls minimist` 查看了一下 minimist的依赖关系，发现有好几层，不知该怎么操作？
<img width="327" alt="截屏2020-06-07 上午11 07 03" src="https://user-images.githubusercontent.com/49122192/83965920-05e72900-a8af-11ea-97bd-82396dc1e14b.png">

**Comment by JoeyBling** [comment]
这个是有些依赖插件有不安全的使用版本，github帮你检测出来了并通知你，可以暂时忽略问题，

**Comment by SuyueLiu** [comment]
好的，谢谢
