### ISSUE TITLE
valine评论系统

### ISSUE THREAD

**Issue by huangjingping520** [JoeyBling/hexo-theme-yilia-plus#53]
想请问作者能否更改支持valine评论系统

**Comment by JoeyBling** [comment]
暂时没考虑支持，可以自己参考其他评论配置自行添加。
> [畅言、Disqus、Gitment、码云评论配置](https://github.com/JoeyBling/hexo-theme-yilia-plus/wiki/%E7%95%85%E8%A8%80%E3%80%81Disqus%E3%80%81Gitment%E3%80%81%E7%A0%81%E4%BA%91%E8%AF%84%E8%AE%BA%E9%85%8D%E7%BD%AE)
