### ISSUE TITLE
每次点击主页，都会产生新的标签页

### ISSUE THREAD

**Issue by toprocker** [JoeyBling/hexo-theme-yilia-plus#6]

**Comment by toprocker** [comment]
我试着把 open_in_new改为了false，但问题并没有被解决

**Comment by JoeyBling** [comment]
> 问题并没有被解决

是的，主页我默认是新标签页打开，没有使用配置项进行控制
我等会改一下，使用配置项进行控制，今天晚上前会更新

**Comment by JoeyBling** [comment]
@toprocker 已修改，请使用主题配置项进行控制 `open_in_new`
