### ISSUE TITLE
主页没有对文章进行裁剪

### ISSUE THREAD

**Issue by shouzheng** [JoeyBling/hexo-theme-yilia-plus#7]
## ❓问题

主页显示的内容应该是经过裁剪的，以“显示更多”的形式查看全文，我看到你的博客也是这样的。
但是我在使用了你的主题之后，发现主页的内容并没有按照预期的进行裁剪，排查了很久也没发现原因。

请参考：[我的博客](http://heyikan.com/)

## 🤔结果 & 预期

Please describe what you expected to see.(请描述一下你希望看到什么)

## 🐥环境 & 设置

**Node.js & npm version**

```bash
```

**Your site `_config.yml`** (Optional)

```yml
```

**Your theme `_config.yml`** (Optional)

```yml
```

**Your browsers** (Optional)

> The browser you use

**Your OSes** (Optional)

> what platforms (operating systems and devices) are affected?

**Comment by JoeyBling** [comment]
@shouzheng 你有在md文件里设置 ```<!--more->``` 吗？

**Comment by shouzheng** [comment]
你是对的，谢谢~
