### ISSUE TITLE
建议添加的功能

### ISSUE THREAD

**Issue by yansheng836** [JoeyBling/hexo-theme-yilia-plus#8]
## Feature Request
1. 各种类型的代码块语法高亮，手机端设置超长代码不超出屏幕（即超出可以显示向右滑动框）。
2. 优化“代码块的行数在屏幕变小时会发生错乱（如手机端）”问题。
3. 能否优化文中超链接的样式？

**Comment by JoeyBling** [comment]
@yansheng836 非常感谢您的反馈，关于第三个问题能详细再说明一下吗？（具体如何优化）
> 再次谢谢您的宝贵意见

**Comment by yansheng836** [comment]
> @yansheng836 非常感谢您的反馈，关于第三个问题能详细再说明一下吗？（具体如何优化）
> 
> > 再次谢谢您的宝贵意见

可参考：
1. github-Hover ：<https://github.com/IanLunn/Hover>，效果：<http://ianlunn.github.io/Hover/>
2. github-cssfx :  <https://github.com/jolaleye/cssfx> ,效果：<https://cssfx.dev/>

**Comment by yansheng836** [comment]
问题1,2：可参考：<https://www.jianshu.com/p/adb7640c97c2>这篇文章的`修改代码块样式`和`代码块行号显示错乱`，当我我觉得这个样式还有待改进。

还有就是（修改后）这里的代码块过长支持向右滑动查看，但是它的默认的滑动条好像不明显。不知道能不能修改其样式？

后面我发现不至代码块会出现字符超长会被隐藏，“引用块”也会，而且这个好像没有设置像代码块那样截断的，也许添加类似样式可以实现优化。

引用块问题如下：

（1）电脑F12缩小屏幕时：
![image](https://user-images.githubusercontent.com/45334066/63212264-5761d400-c134-11e9-957b-45a6a08c2a18.png)
---
（2）电脑F12模拟手机屏时：
![image](https://user-images.githubusercontent.com/45334066/63212278-80826480-c134-11e9-9866-c955d84067dd.png)

**Comment by JoeyBling** [comment]
@yansheng836 非常感谢你的这几个反馈，这几天我会再看看有需要优化的地方，研究一下

**Comment by JoeyBling** [comment]
@yansheng836 已解决以下反馈
1. 代码块行号颜色样式
2. 代码行数显示错乱问题已解决(代码块过长支持向右滑动查看，且滑动条明显可见)
3. 超链接过长自动换行

**Comment by JoeyBling** [comment]
你反馈的“引用块过长”问题在我这里是没有问题的，要不你再测试一下

**Comment by yansheng836** [comment]
调整样式，设置超长自动截断：

```css
/* 如果超长，自动截断 */
word-wrap:break-word;
word-break:break-all;
```

超链接：
![image](https://user-images.githubusercontent.com/45334066/68071380-f5208300-fdb4-11e9-93eb-e1de11c484bf.png)

引用块：
![image](https://user-images.githubusercontent.com/45334066/68071386-fe115480-fdb4-11e9-8092-2c7a2bdfb5ed.png)
